buffer.tab_width = 4
buffer.use_tabs = true
buffer.wrap_mode = buffer.WRAP_WORD
buffer.view_ws = buffer.WS_VISIBLEALWAYS
buffer.virtual_space_options = buffer.VS_NONE
buffer.wrap_visual_flags = buffer.WRAPVISUALFLAG_MARGIN
buffer.whitespace_size = 2
buffer.multi_paste = buffer.MULTIPASTE_EACH
local INDIC_BRACEMATCH = textadept.editing.INDIC_BRACEMATCH
buffer.indic_style[INDIC_BRACEMATCH] = buffer.INDIC_DOTBOX
buffer.indic_alpha[INDIC_BRACEMATCH] = 255
local INDIC_HIGHLIGHT = textadept.editing.INDIC_HIGHLIGHT
buffer.indic_alpha[INDIC_HIGHLIGHT] = 255
buffer.indic_style[INDIC_HIGHLIGHT] = buffer.INDIC_BOX
